version: "3.9"
services:

  jupyter-lab:
    image: data-science-stack:2.9.0
    environment:
      - NOTEBOOKS_TOKEN=${NOTEBOOKS_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./notebooks:/notebooks
    ports:
      - "8888:8888"
      - "8787:8787"
      - "8786:8786"
